### ISSUE TITLE
REST API should be exposed

### ISSUE THREAD

**Issue by berkayerten** [gokhandegerli/EngCompany#1]
As a client of this Web API, I would like to see all the endpoints available

Swagger could be used as an option

**Comment by gokhandegerli** [comment]
@codeSpiritX 
This task has been delayed due to the problems of the latest version of Swagger, to be solved in the future

**Comment by gokhandegerli** [comment]
Tekrar inceledim ve denedim, IntelliJ 2.6.4 gibi versiyonda çalıştırmayı başardım, fakat onda da anladığım kadarıyla üzerine pek geliştirme yapılmadığı için çeşitli buglar ile karşılaşıyoruz (bazı endpointler istenilen sonucu dönmüyor vs), bu durumda ciddi bir güncelleme ya da düzeltme gelmeden kullanmanın pek mantıklı olduğunu düşünmüyorum.

**Comment by berkayerten** [comment]
Tamam simdilik bu ticket'i kapatiyorum. Ileride tekrar acmamiz gerekecektir

**Comment by berkayerten** [comment]
Tamam simdilik bu ticket'i kapatiyorum. Ileride tekrar acmamiz gerekecektir
